<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Configurations>Debug;Release;MELON;BEPIN</Configurations>
    <Platforms>AnyCPU</Platforms>

    <BEPINEX>$(MSBuildProjectDirectory)/lib/BepInEx</BEPINEX>
    <MELONLOADER>$(MSBuildProjectDirectory)/lib/MelonLoader</MELONLOADER>
  </PropertyGroup>


  <ItemGroup Condition="'$(Configuration)'=='MELON' Or '$(Configuration)'=='Debug'">
    <Reference Include="MelonLoader">
      <HintPath>$(MELONLOADER)/net6/MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(MELONLOADER)/net6/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MELONLOADER)/net6/Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/Unity.Netcode.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(MELONLOADER)/Il2CppAssemblies/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
  </ItemGroup>


  <ItemGroup Condition="'$(Configuration)'=='BEPIN' Or '$(Configuration)'=='Release'">
    <Reference Include="BepInEx.Core">
      <HintPath>$(BEPINEX)/core/BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(BEPINEX)/core/BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(BEPINEX)/core/Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX)/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppSystem" Condition="Exists('$(BEPINEX)/interop/Il2CppSystem.dll')">
      <HintPath>$(BEPINEX)/interop/Il2CppSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib" Condition="Exists('$(BEPINEX)/interop/Il2Cppmscorlib.dll')">
      <HintPath>$(BEPINEX)/interop/Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>$(BEPINEX)/interop/Unity.Netcode.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>$(BEPINEX)/interop/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(BEPINEX)/interop/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(BEPINEX)/interop/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(BEPINEX)/interop/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(BEPINEX)/interop/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(BEPINEX)/interop/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='MELON' Or '$(Configuration)'=='Debug'">
    <DefineConstants>MELON</DefineConstants>
    <AssemblyName>CustomNight_MELON</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='BEPIN' Or '$(Configuration)'=='Release'">
    <DefineConstants>BEPIN</DefineConstants>
    <AssemblyName>CustomNight_BEPINEX</AssemblyName>
  </PropertyGroup>

  <Target Name="CopyToModsMELON" AfterTargets="Build" Condition="'$(Configuration)'=='MELON' Or '$(Configuration)'=='Debug'">
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="/home/void/Games/fnaf-online/Mods/" />
  </Target>

  <Target Name="CopyToModsBEPIN" AfterTargets="Build" Condition="'$(Configuration)'=='BEPIN' Or '$(Configuration)'=='Release'">
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(BEPINEX)/plugins/" />
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="assets\blip.wav" />
  </ItemGroup>

</Project>